"""Audit nama entry point terhadap disiplin dua-bukti.

Dari C:\\Projects\\DOS-Decompiler SKILL.md:
  "Never commit a function name on one source of evidence. Two independent kinds
   of evidence agreeing earns confidence; one kind stays provisional and gets a
   __maybe suffix. ... a sibling project kept a table of 35 conclusions it had to
   retract, and the pattern was explicit: single-source conclusions almost always
   need correcting."

Jenis bukti yang dihitung di sini, dan harus BERBEDA JENIS:
  S  struktur tubuh rutin        (apa yang kodenya lakukan)
  L  literal yang diterima       (argumen string di situs panggilan)
  F  akumulator bersama tetap    (alamat dipakai banyak rutin runtime berbeda)
  T  pemetaan ukuran->tipe        (tabel stub: AL=4 => SINGLE, dst)
  V  peran variabel dari luar     (arti sebuah alamat ditetapkan oleh rutin LAIN)

  X (kecocokan tanda tangan antar-biner) SENGAJA DIHAPUS sebagai jenis bukti.
  Nama di biner saudara diturunkan lewat transfer DARI nama di sini, jadi
  memakainya balik adalah melingkar -- satu sumber didandani jadi dua.
  Lihat NEGATIVE-RESULTS.md sec. 9.
  A  pola/arity argumen          (berapa argumen, nilai apa)
  P  pasangan                    (pencacah naik/turun berpasangan)
  D  deskriptor stub             (byte AL/AH di tabel stub)
"""
import json,os,collections

ROOT=r"C:\Users\aguna\Downloads\Personal\Games\old_games\decompile"

# (nama, {jenis: alasan})
EV = {
 "PAC-GAL.EXE": {
  31168:("RT_HEAPINIT", {"S":"membaca PSP:[2] -- kata batas memori yang diberikan DOS -- lalu memasang ds/es ke segmen DGROUP dan menghitung bp = puncak - 0x10; tak menyentuh satu pun variabel pengguna",
                       "P":"byte demi byte IDENTIK di ketiga biner, hanya konstanta segmennya berbeda (PAC-GAL 0x7a2, 3DTTT 0xb11, HOPPER 0x7c5)",
                       "A":"selalu panggilan PERTAMA kode pengguna, di situs 26, mendahului RT_STMTCTX dan TRAP_INIT"}),
  17458:("RT_STMTCTX",  {"S":"`mov al,5` ke satu byte konteks lalu mencatat sp ke kata titik-periksa pernyataan, kemudian memulihkan alamat kembali jauh -- pembukuan, tanpa keluaran",
                       "P":"bentuk yang sama persis di ketiga biner, hanya alamat datanya berbeda (PAC-GAL [0x20]/[0x1e], 3DTTT [0xba]/[0xb8], HOPPER [0xb8]/[0xb6])",
                       "A":"selalu panggilan KEDUA kode pengguna, di situs 38"}),
  14247:("END_STMT",    {"S":"jalur `clc / pushf / <rantai pembersih> / popf / jmp` -- kembar dari entry luar @14238 yang menguji bendera lebih dulu dan mengambil jalur `stc`; carry itulah yang membedakan dua ragam terminasi",
                       "A":"entry DALAM dipanggil dari TENGAH program (pernyataan END eksplisit), entry LUAR tepat satu kali di situs panggilan TERAKHIR kode pengguna -- terminator implisit di ujung program",
                       "P":"pasangan yang sama ada di ketiga biner: PAC-GAL 14238/14247, 3DTTT 31384/31393, HOPPER 15089/15098"}),
  22732:("PRINT_USING", {"S":"`mov word [0x624],0 / mov byte [0x80c],0` lalu jmp ke pemasang penangan keluaran -- membersihkan format lama lalu memasang yang baru; ia tidak mencetak apa pun sendiri",
                       "V":"argumen satu-satunya adalah string '&', yaitu penentu medan STRING panjang-bebas PRINT USING -- tak punya arti lain",
                       "P":"bentuk dua-simpan-lalu-lompat yang sama dengan @23194 di HOPPER, yang argumennya juga string format"}),
  14238:("END_STMT",  {"S":"`mov bl,0x13 / cmp [0x62b],0` lalu clc/pushf, rantai pembersih, popf, jmp -- penutup program",
                       "P":"bentuk yang sama ada di 3DTTT @31384 dan HOPPER @15098; situsnya tepat sesudah RETURN terakhir alur permainan"}),
  # --- lahir dari rekompilasi bisa-jalan (lihat RUNNABLE.md) ---
  14465:("RND",        {"S":"generator kongruensi linear: rantai mul atas benih 32-bit di [0x22]/[0x2a] dan [0x24]/[0x2c], hasilnya dirakit di bx",
                        "A":"argumennya di-dispatch persis seperti RND(X) GW-BASIC -- `cmp byte [bx+3],0` menangkap eksponen nol (X=0, kembalikan yang terakhir) dan `test byte [bx+2],0x80` menangkap tanda (X<0, benihi ulang)"}),
  14595:("RANDOMIZE",  {"S":"seluruh tubuhnya `mov word [0x2b], bx` lalu retf -- menulis satu word ke tengah benih",
                        "F":"[0x2a]..[0x2d] adalah akumulator yang DIBACA RND @14465; penulisnya cuma rutin ini, dan situsnya menerima nilai turunan TIME$"}),
  19834:("SOUND",      {"S":"`cmp bx, 0x25` menolak argumen di bawah 37 -- persis batas bawah frekuensi SOUND GW-BASIC, bukti yang sama seperti SOUND HOPPER @11523",
                        "A":"bx = frekuensi bulat (4000, 150) dan dx = alamat konstanta MBF durasi (0.2, 0.1); dua operan bertipe beda, sesuai SOUND freq,durasi"}),
  16985:("STRTEMP",    {"S":"`mov dl,3` adalah kode tipe STRING di tabel deskriptor, lalu mengalokasikan rekaman dan menyalin deskriptor bx ke dalamnya",
                        "A":"setiap situsnya persis mendahului CONCAT$ dan menyediakan operan yang dibaca CONCAT$ dari ax"}),
  22142:("INPUT_ITEM", {"S":"memanen alamat kembali jauh (`pop di`/`pop es`) lalu membaca DUA byte sebaris, byte kedua ditranslasi lewat tabel di 0xEC",
                        "D":"byte sebaris kedua adalah kode tipe deskriptor: 4 = SINGLE di satu-satunya situsnya, cocok dengan prompt `How fast (0-30000)` yang meminta angka"}),
  22341:("INPUT_DONE", {"S":"menelusuri MUNDUR penyangga item di [0x702] dan menguji `cmp cl,3`, yaitu memproses daftar item yang sudah dikumpulkan",
                        "P":"selalu menutup pasangan INPUT @21265 + INPUT_ITEM @22142, dan bx-nya adalah alamat variabel tujuan"}),
  # --- koreksi: @20299 sempat dinamai LOCATE dan itu keliru ---
  20299:("COLOR_FG",   {"S":"validator argumennya @20500 memakai si=0xDE/ch=3 lalu si=0xE3/ch=4 -- tabel batas keluarga COLOR; LOCATE memakai validator LAIN, @13039 dengan si=0xB3/ch=5",
                        "V":"situsnya selalu berpasangan dengan @20325 dan membawa 15, 7, atau 26. Sebagai baris layar 26 mustahil dan memang melempar Illegal function call; sebagai atribut warna ketiganya sah"}),
  20325:("COLOR_BG",   {"S":"berbagi validator @20500 dengan @20299 dan selalu menjadi argumen KEDUA di situs yang sama",
                        "P":"pasangan tetap: tiap @20325 didahului tepat satu @20299, pola arity yang sama seperti pasangan LOCATE baris/kolom"}),
  # --- koreksi: satu nama STRING$ menutupi dua konvensi ---
  16929:("STRING$_C",  {"S":"mendorong dx apa adanya ke pembentuk string -- dx adalah KODE karakter",
                        "A":"dx di situsnya selalu angka kecil (205, 223, 220, 1), tak pernah alamat deskriptor sah"}),
  16936:("STRING$_S",  {"S":"`cmp word [bx],0` lalu `mov bx,[bx+2]` dan `mov al,[bx]` -- membaca panjang dan penunjuk deskriptor, jadi dx adalah ALAMAT string",
                        "A":"dx di situsnya selalu alamat variabel string yang sudah ditugasi (2520, 2556)"}),
  17484:("TRAP_INIT", {"S":"menolkan tepat 0x69 = 105 byte mulai 0x637, lalu membersihkan byte di 0x636",
                        "V":"pembantu PAC-GAL sendiri di 0x459A memakai mov bx,0x637; mov ah,5; mul ah -- basis dan langkah 5 byte yang sama, jadi 105 byte itu 21 rekaman"}),
  20527:("KEY_DISPLAY",{"S":"memetakan argumennya ke salah satu dari tiga keadaan {0,1,2}, membandingkannya dengan byte status [0x71], menuliskannya balik, dan memanggil rutin penerap HANYA bila keadaannya berubah",
                        "V":"penerap di 20687 menempatkan kursor pada dh=0x18 yaitu baris 24, baris TERBAWAH layar, lalu bila status bernilai nol mengisi cl=[0x6F6] karakter -- selebar layar penuh -- lewat BIOS ah=9. Itu baris tombol fungsi yang dikosongkan. Region 20687-20728 dibongkar sendiri"}),
  # --- jebakan peristiwa (iterasi #20), diturunkan dari disassembly PAC-GAL sendiri ---
  17968:("ON_KEY_GOSUB",{"S":"menguji argumen terhadap batas kelas lalu menyimpan alamat penangan jauh ke [bx+1] dan [bx+3] sebuah rekaman berukuran 5 byte",
                        "V":"penangan INT 9 PAC-GAL di 17830 membaca port 0x60, mengurangi 0x3B kode pindai F1, dan membatasi 10 tombol fungsi -- region itu dibongkar sendiri"}),
  18028:("KEY_ONOFF", {"S":"menguji bx dalam 1..14 lalu memakai dl untuk memilih satu dari tiga jalur -- ON, OFF, STOP",
                        "P":"memakai indeks dasar kelas cl=3 yang sama dengan ON_KEY_GOSUB @17968"}),
  21807:("INT2SGL",   {"S":"memuat AH dengan 0x90, eksponen MBF untuk 2^16, mengambil tanda dari bit tinggi bilangan bulat lewat or al,bh, dan me-neg magnitudonya bila negatif -- menyusun MBF mentah dari bilangan bulat 16-bit",
                        "V":"0x2FB4 yang dipanggilnya adalah NORMALIZER mantissa: ia menggeser mantissa ke kiri sambil menurunkan eksponen sampai bit tinggi menyala (12244-12248). Region itu dibongkar sendiri"}),
  15787:("VAL",       {"S":"mov si,[bx+2] mengambil penunjuk DATA dari deskriptor string lalu memanggil pemindai; byte tipe hasil [0x8EA] disetel 8, jadi masukannya string dan keluarannya bilangan",
                        "A":"situs 479 didahului lcall ke LEFT$ @16822 pada rantai TIME$ -- VAL(LEFT$(TIME$,2)), idiom baku membaca jam"}),
  17237:("TIME$",     {"S":"mengalokasi string sepanjang TEPAT 8 lalu membaca DOS int 21h ah=0x2C dan menormalkan hasilnya berjenjang: seperseratus >= 50 membulatkan detik, detik >= 60 menaikkan menit, menit >= 60 menaikkan jam -- 8 adalah panjang persis HH:MM:SS",
                        "A":"hasilnya mengalir ke KETIGA fungsi substring: LEFT$(.,2) di situs 479, MID$(.,cx,4) di 505, dan RIGHT$(.,cx) di 545 -- jadi yang dikembalikan memang string"}),
  # --- trio substring PAC-GAL (iterasi #15), diturunkan dari pengekstrak PAC-GAL sendiri di 17009 ---
  16822:("LEFT$",     {"S":"xor cx,cx menyetel offset awal ke nol",
                        "P":"berbagi pengekstrak 17009 dengan @16831 dan @16845, yang mengapit dx terhadap [bx] dan cx terhadap nol"}),
  16831:("RIGHT$",    {"S":"mov cx,[bx]; sub cx,dx menyetel offset awal ke panjang dikurangi cacah",
                        "P":"berbagi pengekstrak 17009"}),
  16845:("MID$",      {"S":"dec dx lalu apit awal DAN cacah terhadap panjang -- bentuk dua argumen",
                        "P":"berbagi pengekstrak 17009"}),
  20174:("CLS",        {"S":"memilih dl=0x27 (39) atau dl=0x4F (79) menurut lebar layar, dh=0x18 (24), lalu BIOS int 10h ah=6 dengan al=0 -- gulung-ke-atas nol baris, yaitu mengosongkan seluruh persegi (0,0)-(24,lebar)",
                        "V":"[0x6F6] terbukti lebar layar dari rutin SCREEN @21120, yang dibongkar sendiri di iterasi #9"}),
  21120:("SCREEN",     {"S":"uji jangkauan baris < 25/26 dan kolom terhadap lebar layar [0x6F6]; dec dh/dec dl mengubah koordinat BASIC 1-berbasis ke 0-berbasis; lalu BIOS ah=2 (tempatkan kursor) diikuti ah=8 (baca karakter dan atribut). Di 21187 argumen KETIGA memilih hasil: inc cl/je melompati mov al,ah, jadi cl kosong -> kode karakter, cl terisi -> atribut warna. Itu persis semantik SCREEN(baris,kolom[,warna])",
                        "A":"12 situs dengan argumen baris/kolom di bl/dl"}),
  # --- keluarga aritmetika, salin-FAC, dan pembanding (iterasi #8) ---
  12004:("ADD!",       {"S":"cmp ch,ah lalu selisih eksponen dan penjaga cmp ah,0x18 -- 0x18 = 24 = bit mantissa MBF presisi TUNGGAL; penyelarasan penjumlahan, tanpa xor al,cl",
                        "T":"0x18 di sini berpasangan dengan 0x38 di ADD# @14638 pada biner yang sama"}),
  11999:("ADD!_FAC",   {"F":"si = 0x1A = FAC tunggal PAC-GAL",
                        "P":"jmp ke 12010, tubuh ADD! yang sama"}),
  14638:("ADD#",       {"S":"selisih eksponen dengan penjaga cmp ah,0x38 = 56 bit mantissa presisi ganda; operan dibaca di [di+6]/[si+6]",
                        "F":"di = 0x16 = FAC ganda"}),
  14633:("ADD#_FAC",   {"F":"si = 0x16 = FAC ganda",
                        "P":"jmp ke 14644, tubuh ADD# yang sama"}),
  12779:("FACSTORE!",  {"S":"simpan si,di ke [0x5F6]/[0x5F8]; si:=0x1A lalu DUA movsw dari FAC ke memori pemanggil; pulihkan",
                        "T":"dua movsw = 4 byte = presisi tunggal"}),
  12804:("FACSTORE#",  {"S":"struktur identik @12779 tetapi si:=0x16 dan EMPAT movsw",
                        "T":"empat movsw = 8 byte = presisi ganda"}),
  15731:("FCMP!",      {"S":"std lalu repe cmpsw -- perbandingan MUNDUR mulai word paling berarti; xor bl,al menggabung tanda kedua operan dan rcl memindah tanda ke carry, jadi hasilnya bendera banding bertanda",
                        "T":"mov cx,2 menggeser si/di ke byte eksponen operan 4-byte; entry tetangga di 15721 memakai add di,6 untuk operan 8-byte"}),
  15726:("FCMP!_FAC",  {"F":"si = 0x1A = FAC tunggal",
                        "P":"jmp ke 15737, tubuh FCMP! yang sama"}),
 },
 "HOPPER.EXE": {
  31728:("RT_HEAPINIT", {"S":"membaca PSP:[2] -- kata batas memori yang diberikan DOS -- lalu memasang ds/es ke segmen DGROUP dan menghitung bp = puncak - 0x10; tak menyentuh satu pun variabel pengguna",
                       "P":"byte demi byte IDENTIK di ketiga biner, hanya konstanta segmennya berbeda (PAC-GAL 0x7a2, 3DTTT 0xb11, HOPPER 0x7c5)",
                       "A":"selalu panggilan PERTAMA kode pengguna, di situs 26, mendahului RT_STMTCTX dan TRAP_INIT"}),
  19801:("RT_STMTCTX",  {"S":"`mov al,5` ke satu byte konteks lalu mencatat sp ke kata titik-periksa pernyataan, kemudian memulihkan alamat kembali jauh -- pembukuan, tanpa keluaran",
                       "P":"bentuk yang sama persis di ketiga biner, hanya alamat datanya berbeda (PAC-GAL [0x20]/[0x1e], 3DTTT [0xba]/[0xb8], HOPPER [0xb8]/[0xb6])",
                       "A":"selalu panggilan KEDUA kode pengguna, di situs 38"}),
  15089:("END_STMT",    {"S":"jalur `clc / pushf / <rantai pembersih> / popf / jmp` -- kembar dari entry luar @15098 yang menguji bendera lebih dulu dan mengambil jalur `stc`; carry itulah yang membedakan dua ragam terminasi",
                       "A":"entry DALAM dipanggil dari TENGAH program (pernyataan END eksplisit), entry LUAR tepat satu kali di situs panggilan TERAKHIR kode pengguna -- terminator implisit di ujung program",
                       "P":"pasangan yang sama ada di ketiga biner: PAC-GAL 14238/14247, 3DTTT 31384/31393, HOPPER 15089/15098"}),
  15446:("RANDOMIZE", {"S":"seluruh tubuhnya `mov word [0xc3], bx` lalu retf -- satu simpanan ke kata benih",
                       "V":"[0xc3] berada di dalam kata benih yang DIBACA generator RND @15316 ([0xc2] dan [0xc4] dikalikan [0xba]/[0xbc])",
                       "A":"argumennya rantai MID$/VAL/CINT# atas TIME$ -- benih dari jam, idiom RANDOMIZE yang baku"}),
  13450:("SGN",       {"S":"membaca kata TINGGI float di [si+2] lalu jatuh ke tubuh bersama yang menyetel `ah=0x81` dan `and al,0x80`: eksponen 1.0 dengan HANYA bit tanda yang dipertahankan, dan nol bila eksponennya nol -- itu +1/0/-1",
                       "A":"hasilnya langsung diumpankan ke SGNTEST_FAC lalu `mov bx,0 / jae / dec bx`, yang menerbitkan perbandingan `>= 0`"}),
  22114:("PAINT",     {"S":"memasang tumpukan isi-banjir berbatas dari [0x7fa]: membaca panjang berprefiks, menjaganya dengan `cmp ax,0x1000`, lalu menyetel kata mulai/akhir/kursor di [0x7cd]..[0x7d3] -- PSET @20297 tak punya struktur semacam itu sama sekali",
                       "V":"helper khasnya 0x60a3 memperlakukan atribut sebagai OPSIONAL lewat uji tanda (`or al,al / jns`) dengan mundur ke [0x7e0] -- persis atribut batas PAINT yang boleh dihilangkan",
                       "A":"kedua situsnya berada di urutan gambar katak, sesudah PSET+DRAW memasang garis luar, dan argumen warnanya BERBEDA antar situs (2 dan 3) -- perilaku argumen, bukan konstanta rutin"}),
  20073:("TAB",       {"S":"menghitung selisih kolom: `mov ax,bx / dec ax`, membandingkan kolom kini terhadap target (`cmp cl,ch`), dan hanya bergerak MAJU (`jae` melewati) sebelum `sub cl,ch`",
                       "A":"situsnya berada DI DALAM daftar PRINT dengan argumen kecil (12), dan teks yang menyusul adalah ' G A M E   O V E R' -- indentasi penengah",
                       "P":"entry bersebelahan dengan SPC @20039 di badan yang sama; SPC menyisipkan n spasi, TAB pindah ke kolom n"}),
  16553:("ON_ERROR",  {"S":"`mov word [0x64a], bx` lalu retf -- menyimpan satu alamat penangan",
                       "A":"bx pada situsnya bernilai 7441, yang PERSIS alamat situs ON_ERROR_OFF; dan panggilan berikutnya adalah OPEN mode keluaran -- penulisan berkas yang dijaga"}),
  16558:("ON_ERROR_OFF", {"S":"`mov word [0x64a], 0` -- mengosongkan alamat penangan yang dipasang @16553, lalu menguji bendera galat [0x64f] dan memulihkan konteks tersimpan bila ada",
                       "A":"situsnya adalah TUJUAN yang dipasang @16553, dan diikuti langsung CLOSE / CLS / END -- penangan yang mematikan dirinya sendiri lalu menutup program"}),
  21032:("PLAY",      {"S":"mencatat sp ke titik periksa pernyataan lalu melompat ke penafsir dengan alamat rutin tetap di ax",
                       "V":"argumen satu-satunya adalah string 'P2L8C.CL16CL8D.GL16FL8EL4C' -- tata bahasa MML PLAY yang lengkap (P jeda, L panjang, C-G nada, titik untuk not bertitik)"}),
  19815:("CALL_VAR",  {"S":"memanen alamat kembali jauh (`pop di / pop si`), mengambil argumen tumpukan ke bx, lalu mendorong [0x98] dan [bx] sebelum retf -- lompat-jauh ke segmen:offset yang dirakit saat itu juga",
                       "V":"[0x98] adalah kata segmen yang ditulis DEF_SEG= @14556, dan situsnya didahului DEF_SEG= -- pasangan `DEF SEG = s : CALL v` yang baku",
                       "A":"situsnya berada tepat sesudah gelung READ/POKE yang menyuntikkan penggulung 228 byte; itulah kode mesin yang dipanggilnya"}),
  19476:("STICK",     {"S":"memvalidasi 0 <= bx < 4; bx=0 mencabang ke pencuplik di 19490, bx 1..3 mengembalikan byte dari tabel EMPAT entri [bx+0x102] -- pembaca dengan cache, bukan penyampling langsung",
                       "V":"pencuplik di 19490 menjalankan protokol port permainan PC yang baku: dx=0x201, `out dx,al` lalu `in al,dx` di dalam gelung bertempo (cx=0x101) sambil memasker 0x0F -- empat sumbu, empat bit",
                       "A":"kedua situsnya (4660, 4681) berada di cabang yang dipilih prompt 'JOYSTICK OR KEYBOARD (J/K)', dan hasilnya diambang `IF F53! <= 30` -- pemakaian sumbu, bukan tombol"}),
  # --- PRINT USING, EOF, dan penyimpan hasil INPUT ---
  23194:("PRINT_USING",{"S":"memasang penangan keluaran ([0x7d7]=1, [0x7d8]=<offset kode>) lalu kembali tanpa mencetak apa pun -- penyetel format, bukan pencetak",
                       "V":"ketiga argumennya adalah string format PRINT USING yang sah dan HANYA masuk akal sebagai format: '######   ', dan dua prompt yang menaruh nilai berjalan di dalam kurung siku, 'Enter Skill Level (1-4) [#]: ' dan 'Enter Speed (1-500)  [####]: '",
                       "A":"ketiga situsnya langsung diikuti stub PRINT<!;> yang mencetak satu float -- nilai yang mengisi tempat '#' itu"}),
  16870:("EOF",       {"S":"menerima bx = nomor berkas, menyetel titik periksa batas-pernyataan lalu mendelegasikan; hasilnya kembali di bx dan diuji sebagai boolean",
                       "A":"satu-satunya situsnya (1436) adalah PENJAGA gelung yang dibuka `OPEN \"I\"` dan yang tubuhnya melakukan INPUT#/LINE INPUT# dari berkas yang sama; tak ada penghenti lain di blok itu",
                       "V":"diuji sebagai `NOT <hasil> <> 0` untuk MELANJUTKAN gelung -- persis konvensi EOF BASIC, di mana NOT(-1)=0 berhenti dan NOT(0)=-1 lanjut"}),
  22031:("INPUT_DONE",{"S":"membaca penunjuk daftar [0x6BA], mundur dua byte, mengambil word ukuran, mencabang pada kode tipe (`cmp cl, 3`), lalu rep movsw MENYALIN cx/2 word ke [bx] -- ia menulis nilai yang sudah diurai ke alamat tujuan, bukan membukukan tumpukan",
                       "A":"ketiga situsnya di HOPPER langsung mengikuti INPUT_ITEM, dan bx pada tiap situs adalah alamat tujuan yang diisi INPUT (G1!(i) di gelung pembaca papan skor, F21!/F22! di prompt skill dan speed)",
                       "P":"bentuk dan peran yang sama dengan @36318 di 3DTTT, yang juga sempat salah dinamai STKREAD"}),
  # --- I/O berkas skor dan penutup program ---
  17046:("OPEN",      {"S":"menerima bx = nomor berkas, dx = nama berkas, cx = mode dan meneruskannya ke pembuka berkas",
                       "A":"kedua situsnya didahului OPEN_MODE dan diikuti INPUT#_BEGIN atau PRINT# dengan nomor berkas yang sama"}),
  16913:("CLOSE",     {"S":"memanggil helper @17293, helper yang sama dipakai jalur terminasi @15098",
                       "A":"situs 1397 menutup berkas sebelum OPEN berikutnya di 1417 -- pola tutup-lalu-buka"}),
  21832:("INPUT_ITEM",{"S":"memanen alamat kembali jauh (pop di / pop es) lalu membaca DUA byte sebaris dan menyimpan penunjuk daftar item beserta sp -- pengumpul argumen",
                       "A":"ketiga situsnya langsung mengikuti INPUT#_BEGIN dengan nomor berkas di bx"}),
  20039:("SPC",       {"S":"`mov al, 0x20` lalu menulis cx buah karakter itu, dengan jcxz melewati bila nol -- menulis spasi sebanyak argumennya",
                       "A":"kedua situsnya berada DI DALAM daftar PRINT, antara \"SCORE: 0\" dan \"TIME:\", dengan bx = 9"}),
  15098:("END_STMT",  {"S":"`clc / pushf / call <pembersih> / call <helper CLOSE @17293> / popf / jmp` -- menutup berkas lalu mengakhiri program",
                       "P":"bentuk yang sama ada di 3DTTT @31384 dan PAC-GAL @14238"}),
  # --- grafis: GET/PUT/LINE, dipecahkan saat menutup sisa HOPPER ---
  20372:("GET",       {"S":"menghitung |x2-x1|+1 dan |y2-y1|+1 dari dua titik tersimpan ([0x60E]/[0x610] dan [0x612]/[0x614]) lalu menyalin persegi itu ke larik yang ditunjuk bx",
                       "A":"kedua situsnya selalu didahului GFXPT lalu GFXSTART -- tepat dua titik -- dan bx-nya larik yang kemudian dibaca PUT"}),
  20170:("LINE",      {"S":"mendorong kedua titik ke tumpukan lalu memanggil penggambar garis @24994, tanpa perhitungan lebar/tinggi",
                       "A":"cx membawa warna dengan -1 sebagai penanda dihilangkan (helper @27215 menggantinya dengan 3), pola argumen LINE"}),
  20227:("LINE_BF",   {"S":"menghitung lebar |x2-x1|+1 ke [0x6AE] dan tinggi |y2-y1|+1 ke bp, lalu `dec bp / jne` menggambar SEBARIS PENUH piksel per baris -- kotak terisi, bukan garis",
                       "A":"cx = 1 atau -1 di situsnya, argumen warna yang sama seperti @20170"}),
  20466:("GFXPT",     {"S":"memanggil helper @27164 yang menyimpan titik kini ke [0x60E]/[0x610] -- tubuh yang sama persis dengan GFXPT @20155 dan @20360",
                       "P":"selalu mendahului PUT, sebagaimana GFXPT lain mendahului PSET dan DRAW"}),
  # --- lahir dari rekompilasi bisa-jalan (lihat RUNNABLE.md) ---
  13008:("CONCAT$",   {"S":"mov si,ax / mov di,bx lalu bx = [si]+[di] menghitung panjang gabungan, persis mesin penyambung string; salinan pertama dari ax, kedua dari bx",
                       "A":"kedua operannya deskriptor string dan hasilnya mengalir langsung ke DRAW sebagai makro yang sudah dirakit"}),
  20545:("STR$",      {"S":"menyimpan SELURUH akumulator 0xAE..0xB5 ke tumpukan, memanggil pemformat, lalu pengalokasi deskriptor string yang sama dipakai CHR$",
                       "D":"byte tipe [0x874] disetel 4 = SINGLE, jadi masukannya bilangan dan keluarannya string"}),
  15316:("RND",       {"S":"argumen di-dispatch lewat cmp byte [bx+3],0 (eksponen nol) dan test byte [bx+2],0x80 (tanda), lalu rantai mul atas benih 32-bit di [0xBA]/[0xC2]/[0xC4]",
                       "A":"hasilnya selalu melewati INT lalu STR$ untuk kode warna DRAW 1..3 -- jangkauan yang hanya masuk akal bila keluarannya pecahan 0..1"}),
  18724:("INSTR",     {"S":"menukar bx dan dx lalu menyetel bx=1 sebelum memanggil worker; posisi awal 1 adalah bentuk baku INSTR(1, a$, b$)",
                       "A":"dua operan string dan hasil INTEGER yang langsung dikonversi INT2SGL -- hanya INSTR yang berbentuk (int,$,$) -> int"}),
  13638:("INT",       {"S":"helper @13817 memuat operan ke FAC, lalu uji eksponen [0xB5] dan TANDA [0xB4] memilih koreksi @13790 yang menegasikan dua-komplemen -- pembeda INT (pembulatan ke bawah) dari FIX",
                       "A":"di KETUJUH situsnya hasilnya mengalir ke aritmetika float berikutnya dan tak pernah ke lompatan bersyarat, jadi ia mengembalikan NILAI bukan bendera"}),
  # --- koreksi: tiga rutin keluarga pernyataan salah dinamai LOCATE ---
  11988:("COLOR_FG",  {"S":"validator argumennya memakai ch=3 lalu ch=4 -- tabel batas keluarga COLOR; LOCATE memakai ch=5",
                       "P":"pasangan tetap dengan @12014 di situs yang sama, pola arity yang sama seperti pasangan LOCATE baris/kolom"}),
  12557:("SCREEN_A",  {"S":"validator argumennya memakai ch=4 -- tabel batas keluarga SCREEN",
                       "V":"@12583 menyimpan sp lebih dulu sehingga ia entry yang MENGEKSEKUSI; urutan B,A,B di situs 918-933 menghasilkan SCREEN 0 lalu SCREEN 1,0, satu-satunya mode yang membuat DRAW dan PSET sah"}),
  12583:("SCREEN_B",  {"S":"berbagi validator ch=4 dengan @12557 dan mengawali dengan mov [0x636],sp -- penanda entry yang menjalankan pernyataan",
                       "A":"argumen yang dibawanya di situs 918 dan 933 adalah 0 lalu 0, dengan @12557 menyumbang 1 di antaranya"}),
  # --- keluarga READ HOPPER, ditemukan lewat PROFIL eksekusi (tools/hotspot.py) ---
  19921:("READ!",     {"S":"menyetel byte tipe [0x874] lalu masuk tubuh bersama di 19947 yang memindai teks dari penunjuk di [0x6AC], menguji pemisah koma 0x2C, dan memajukan penunjuk itu -- penunjuk yang bertahan antar panggilan, tanpa satu pun panggilan perangkat",
                        "D":"keempat entry menulis {4,8,2,3} ke [0x874], kode tipe yang mapan; [0x874] adalah byte tipe hasil yang sama yang disetel VAL @17620 ke 8"}),
  19928:("READ#",     {"S":"entry sama menyetel [0x874]=8","D":"8 = presisi ganda"}),
  19935:("READ%",     {"S":"entry sama menyetel [0x874]=2","D":"2 = bilangan bulat"}),
  19942:("READ$",     {"S":"entry sama menyetel [0x874]=3 lalu jatuh langsung ke tubuh bersama","D":"3 = string"}),
  14578:("CLEAR",     {"S":"ukuran dibakukan ke 0x200 dan ditolak bila di bawah 0x180; batas dibulatkan ke alamat genap lewat inc bx; and bl,0xFE",
                        "V":"di 14637 ia membandingkan terhadap [0x624] dan di 14646 menulis [0x626] -- basis dan puncak heap HOPPER, keduanya ditetapkan di iterasi #9 dari penelusuran alokator di 25684-26262"}),
  12329:("KEY_ASSIGN",{"S":"menguji argumen dalam 1..10 lalu menghitung 0x16 + (n-1)*4 -- entri ke-n dalam tabel berbasis 0x16 berlangkah 4 byte",
                        "V":"@12243 di biner yang SAMA menyusuri tabel itu: mov bx,0x16, mov cx,0xA sepuluh entri, membaca panjang di [bx] dan penunjuk di [bx+2], lalu add bx,4 di 12295. Region 12243-12298 dibongkar sendiri",
                        "A":"situsnya berada di dalam gelung yang menaikkan pencacah tombol satu per satu dengan string KOSONG sebagai nilai -- mematikan definisi kesepuluh tombol fungsi di awal program"}),
  12243:("KEY_LIST",  {"S":"memancarkan huruf F, nomor, dan spasi untuk sepuluh entri, lalu isi tiap string lewat deskriptornya",
                        "T":"add bx,4 menegaskan langkah 4 byte per entri: word panjang plus word penunjuk"}),
  12216:("KEY_DISPLAY",{"S":"tiga keadaan {0,1,2} disimpan di byte status [0x11], penerap dipanggil hanya bila berubah",
                        "V":"penerap di 12376 menempatkan kursor pada baris 0x18 = 24 dan, bila status nol, mengisi selebar [0x616] lewat BIOS ah=9 -- pengosongan baris tombol fungsi di dasar layar"}),
  19827:("LINE_INPUT",{"S":"memasang penangan di [0x634] lalu memanggil LEWAT vektor pengambil karakter di [0x6B4], mengumpulkan ke penyangga baris 0x6C2, dan membangun string dari isinya",
                        "P":"berpasangan dengan INPUT @20759: keduanya membaca satu baris, tetapi INPUT membawa deskriptor format SEBARIS (tools/inline.py menandainya) sedangkan @19827 TIDAK membawa apa pun -- ketiadaan daftar format itulah tanda LINE INPUT. Vektor [0x6B4] sendiri terbukti pengambil karakter karena INPUT#_BEGIN @20835 yang memasangnya"}),
  13841:("INPUT$",    {"S":"cmp bl,0xFF menguji nomor berkas yang DIHILANGKAN; memetakan nomor berkas ke blok kendali lewat 0x6986, menolak mode 2, lalu xchg word ptr [0x648],si MENUKAR penunjuk perangkat sehingga yang lama bisa dipulihkan, dan mengalokasi string sepanjang cacah yang diminta pemanggil",
                        "P":"memakai pemeta nomor-berkas 0x6986 dan uji mode yang sama dengan INPUT#_BEGIN @20835 dan PRINT# @23272, tetapi mengalokasi string berpanjang tertentu -- itu yang membedakan INPUT$ dari keduanya"}),
  20366:("GFXSTART",  {"S":"meratakan koordinat lalu menyalin pasangan titik-kini [0x60E]/[0x610] ke [0x612]/[0x614] sesudah mengapitnya -- menjadikan titik itu AWAL garis",
                        "V":"[0x612]/[0x614] terbukti pasangan titik awal garis karena 27195 dan 27206 mengambil selisih mutlak terhadapnya untuk Bresenham; region itu dibongkar sendiri di iterasi #13"}),
  20360:("GFXPT",      {"S":"tubuhnya call 0x33B7 lalu jmp 0x6A1C -- perata koordinat yang menambahkan basis STEP, menyimpan titik kini, dan mengapit ke batas layar",
                        "P":"tubuh IDENTIK byte-per-byte dengan GFXPT @20155, entry ganda ke rutin yang sama"}),
  20835:("INPUT#_BEGIN",{"S":"memetakan nomor berkas ke blok kendali lewat 0x6986, menolak deskriptor bermode 2 dengan cmp byte ptr [si],2, menyimpan bloknya ke [0x648], lalu memasang vektor pengambil karakter di [0x6B4]",
                        "P":"menulis [0x648], slot perangkat yang SAMA yang dinolkan PRINT_BEGIN @23248 dan diisi PRINT# @23272 -- tetapi menerima mode yang berlawanan"}),
  16975:("OPEN_MODE$",{"S":"menolak string kosong, mengambil karakter pertama data deskriptor, membesarkannya dengan and bl,0xDF, memetakan ke empat nilai, lalu MENYIMPAN hasilnya ke [0x6A4] -- slot mode berkas yang sama yang ditulis OPEN_MODE @17031 dari indeks numerik",
                        "L":"keempat literal 0x49 I, 0x4F O, 0x52 R, 0x41 A adalah huruf mode OPEN BASIC; sesudahnya memanggil pelepas string sementara 0x65E9, jadi argumennya memang string"}),
  17620:("VAL",       {"S":"mov si,[bx+2] mengambil penunjuk data deskriptor string lalu jmp 0x65E9 -- pelepas string sementara HOPPER yang sudah dibuktikan lewat keluarga LEN/ASC",
                        "D":"menulis 8 ke byte tipe [0x874], kode tipe presisi ganda"}),
  19156:("TIME$",     {"S":"mengalokasi string sepanjang tepat 8 lalu membaca DOS int 21h ah=0x2C dengan normalisasi berjenjang 50/60/60 dari seperseratus ke detik ke menit ke jam",
                        "A":"hasilnya diteruskan ke RIGHT$ dengan dx=2 -- mengambil dua karakter terakhir, yaitu detik"}),
  # --- trio substring HOPPER (iterasi #15), diturunkan dari pengekstrak HOPPER sendiri di 18928 ---
  18741:("LEFT$",     {"S":"xor cx,cx menyetel offset awal ke nol lalu masuk tubuh bersama 18759",
                        "P":"berbagi pengekstrak 18928 dengan @18750 dan @18764; pengekstrak itu mengapit dx terhadap [bx] dan cx terhadap nol, jadi cx memang offset awal dan dx cacah"}),
  18750:("RIGHT$",    {"S":"mov cx,[bx]; sub cx,dx menyetel offset awal ke panjang dikurangi cacah",
                        "P":"berbagi pengekstrak 18928 dengan LEFT$ dan MID$"}),
  18764:("MID$",      {"S":"dec dx mengubah awal 1-berbasis BASIC ke 0-berbasis lalu mengapit AWAL dan CACAH; dua argumen, tak seperti dua saudaranya",
                        "P":"berbagi pengekstrak 18928; jalur string kosongnya mengembalikan deskriptor 0x124 yang sama dengan INKEY$"}),
  # --- grafis CGA (iterasi #13) ---
  20155:("GFXPT",     {"S":"menambahkan basis relatif [0x876]/[0x878] ke operan, menyimpan hasilnya ke pasangan titik-kini [0x60E]/[0x610], MENOLKAN kembali basis relatif itu, lalu mengapit koordinat ke 320 atau 640 kali 200 menurut byte mode layar [0x87]",
                        "V":"[0x876]/[0x878] terbukti basis STEP karena entry @20140 menyalin titik-kini ke dalamnya; [0x60E]/[0x610] terbukti titik-kini karena 27195 dan 27206 mengambil selisihnya terhadap ujung garis. Kedua region dibongkar sendiri di iterasi ini"}),
  20297:("PSET",      {"S":"cmp cx,-1 menguji argumen yang DIHILANGKAN lalu memakai 3 sebagai baku -- indeks warna latar depan CGA; sesudahnya memanggil perata koordinat 27164 dan sepasang rutin gambar titik",
                        "P":"berbagi perata koordinat 27164 dengan GFXPT @20155"}),
  20475:("PUT",       {"S":"MEMBACA lebar di [bx] dan tinggi di [bx+2] -- header larik GET/PUT -- lalu menghitung sudut kanan-bawah dari titik-kini, membagi dua lebarnya bila mode layar lain, dan mengapitnya",
                        "P":"stc sebelum rutin blit 0x5F5A, sedangkan jalur di 20447 memakai clc sebelum rutin yang SAMA dan MENULIS [bx]/[bx+2] alih-alih membacanya -- dua arah berlawanan dari blit yang sama"}),
  13566:("SCALE2!",   {"S":"pop si; pop ds mengambil alamat kembali jauh, lodsb membaca satu byte dari aliran instruksi pemanggil, push ds; push si mendorong balik alamat yang sudah maju; byte itu ditambahkan ke [0xB5], byte eksponen FAC, dengan penjaga agar nol tetap nol",
                        "A":"kedua situs membawa byte sebaris 0x03 dan instruksi sah berikutnya mulai 6 byte sesudah situs"}),
  13545:("ABS",        {"S":"and byte ptr [0xB4], 0x7F membersihkan bit tanda MBF, tanpa efek lain",
                        "F":"0xB4 = 0xB2+2, byte bertanda pada FAC tunggal HOPPER"}),
  13554:("ABS",        {"S":"badan sama dengan @13545 dengan prolog operan berbeda",
                        "P":"berbagi instruksi pembersih tanda yang sama"}),
  # --- string, DEF SEG, tumpukan, dan mode berkas (iterasi #11) ---
  18508:("LEN",        {"S":"push word ptr [bx] mendorong word panjang deskriptor, memanggil pelepas string sementara 0x65E9, lalu pop bx mengembalikan word itu sebagai hasil",
                        "P":"entry tetangga ASC @18515 memakai pelepas sementara yang sama; keduanya beda hanya pada apa yang dikembalikan"}),
  18515:("ASC",        {"S":"cmp word ptr [bx],0 menolak string kosong; mov si,[bx+2] lalu mov si,[si] mengambil word pertama datanya; mov bh,0 menyisakan hanya karakter pertama",
                        "A":"4 situs, satu argumen deskriptor string di bx, hasil dipakai sebagai bilangan di bx"}),
  14556:("DEF_SEG=",   {"S":"menyimpan bx ke [0x98]; entry tetangga @14561 melakukan push [0x98]; push bx; retf -- transfer JAUH yang memakai [0x98] sebagai segmen, jadi slot itu memang nilai segmen, bukan data",
                        "A":"situs panggilan memuat mov bx,0x40 (segmen area data BIOS) dan xor bx,bx (segmen 0) -- dua nilai baku untuk PEEK ke luar segmen BASIC"}),
  14551:("DEF_SEG",    {"S":"menyimpan ds ke [0x98] -- bentuk tanpa argumen yang mengembalikan segmen ke segmen data BASIC",
                        "P":"berbagi slot [0x98] dengan @14556 dan @14561"}),
  14561:("CALL_ABS",   {"S":"inc bx/je menguji penunjuk -1, lalu push word ptr [0x98]; push bx; retf -- memanggil alamat jauh yang tersusun dari segmen [0x98] dan ofset bx",
                        "V":"HOPPER memang memakai CALL ABSOLUTE; rutin penggulung CGA 228 byte-nya sudah dibongkar sendiri di DATA-BLOCKS.md"}),
  17031:("OPEN_MODE",  {"S":"mov cl,bl; mov bl,1; shl bl,cl mengubah indeks argumen menjadi SATU bit, lalu menyimpannya ke [0x6A4]",
                        "V":"[0x6A4] dibaca di 27752/27800/27813 tepat sebelum layanan FCB DOS -- ah=0x13 hapus berkas di 27825 dan ah=0x16 buat berkas di 27827 -- dan sebelum nama FCB 12 byte dirakit dengan rep movsb di 27794. Nilai bit 1/2/4/8 adalah mode berkas BASIC INPUT/OUTPUT/RANDOM/APPEND"}),
  # --- koreksi dan keluarga uji-nol (iterasi #9) ---
  9682:("MUL!",        {"S":"KOREKSI dari STR2OP. Tubuh ini bukan penanganan string: xor al,cl menggabung tanda kedua operan, sub ah,0x81 / add ah,ch menjumlahkan eksponen, dan 9762/9770/9781 berisi tiga mul",
                        "P":"entry @9676 dan @9679 masuk ke tubuh ini; keduanya sudah bernama MUL! atas bukti sendiri"}),
  9671:("MUL!_FAC",    {"F":"si = 0xB2 = FAC tunggal",
                        "P":"jmp ke 9682, tubuh MUL!"}),
  9364:("ADD!",        {"S":"entry lengkap dengan prolog call 0x3397 lalu mov di,0xB2; jatuh ke 9370",
                        "P":"berbagi seluruh tubuh dengan ADD! @9370"}),
  13514:("NONZERO!",   {"S":"xor bx,bx lalu dec bx menghasilkan 0 atau -1 -- FALSE/TRUE milik BASIC; satu-satunya yang diuji adalah byte di [si+3], yaitu byte eksponen, yang bernilai nol tepat ketika bilangannya nol",
                        "T":"offset 3 = byte eksponen operan 4-byte; entry kembar @13524 menguji [si+7], offset eksponen operan 8-byte"}),
  13524:("NONZERO#",   {"S":"struktur identik @13514 tetapi menguji [si+7]",
                        "T":"offset 7 = byte eksponen presisi ganda"}),
  13534:("NONZERO!_FAC",{"F":"menguji [0xB5] = 0xB2+3 = byte eksponen FAC tunggal",
                        "P":"berbagi jalur kembali 0/-1 dengan @13514"}),
  # --- keluarga presisi-ganda dan salin-FAC (iterasi #8) ---
  15490:("ADD#",       {"S":"cmp ch,ah bandingkan eksponen, sub ah,ch/neg ah ambil selisihnya, lalu penjaga cmp ah,0x38 -- 0x38 = 56 = jumlah bit mantissa MBF presisi-ganda; bila selisih melebihi itu operan kecil diabaikan. Penyelarasan seperti ini milik PENJUMLAHAN; tak ada xor al,cl penggabung tanda",
                        "F":"di = 0xAE = FAC ganda, ditetapkan mandiri di iterasi #7"}),
  15485:("ADD#_FAC",   {"F":"si = 0xAE = FAC ganda",
                        "P":"jmp ke 15496, tubuh ADD# yang sama"}),
  13155:("FACSTORE!",  {"S":"simpan si,di pemanggil ke [0x618]/[0x61A]; si:=0xB2 lalu DUA movsw (arah FAC -> memori pemanggil); pulihkan si,di",
                        "T":"dua movsw = 4 byte = presisi tunggal, berpasangan dengan empat movsw di @13180"}),
  13180:("FACSTORE#",  {"S":"struktur identik @13155 tetapi si:=0xAE dan EMPAT movsw",
                        "T":"empat movsw = 8 byte = presisi ganda"}),
  13144:("LOAD#",      {"S":"di:=0xAE menjadikan FAC ganda sebagai TUJUAN (movsw menyalin ds:[si] -> es:[di]); sub si,8 memundurkan penunjuk sumber sepanjang operan",
                        "T":"empat movsw dan mundur 8 byte = presisi ganda; bandingkan sub si,4 di ekor pemuat tunggal @13140"}),
  # --- keluarga kali/bagi + penemuan FAC presisi-ganda (iterasi #7) ---
  9676:("MUL!",       {"S":"eksponen DIJUMLAHKAN: sub ah,0x81 / sub ch,0x80 / add ah,ch di 9706-9712; tubuhnya berisi tiga mul (9762, 9770, 9781) yang merakit hasil-antara 32x32 bit",
                        "P":"xor al,cl menggabung tanda kedua operan -- hanya kali/bagi yang melakukannya; arah eksponen membedakannya dari @9810"}),
  9679:("MUL!",       {"S":"entry yang sama tanpa prolog call 0x3397; jatuh ke tubuh 9682 yang identik",
                        "P":"berbagi seluruh tubuh dengan MUL! @9676"}),
  9810:("DIV!",       {"S":"eksponen DIKURANGKAN: sub ah,0x80 / sub ch,0x80 / sub ah,ch di 9829-9835; di 9897 ada div bx",
                        "P":"kontras langsung dengan MUL! @9676 -- struktur sama persis, hanya arah eksponen dan mul/div yang berbeda"}),
  15894:("MUL#_FAC",  {"S":"operan dibaca di [si+6]/[di+6] -- byte eksponen MBF presisi-GANDA (8 byte), bukan [si]/[di+2] milik presisi tunggal; geseran mantissa shl dx/rcl cx/rcl bx/rcl di = 64 bit",
                        "F":"si=0xAE, tepat 4 byte di bawah FAC tunggal 0xB2 yang sudah ditetapkan -- FAC tunggal adalah paruh atas FAC ganda"}),
  21593:("CINT#",     {"F":"si=0xAE = FAC presisi-ganda",
                        "P":"jmp ke tubuh CINT, jadi keluarannya bilangan bulat"}),
  # --- varian entry ditemukan lewat tools/variants.py (teknik g) ---
  18535:("INKEY$",    {"S":"tiga jalur panjang: bx=0x124 (deskriptor string KOSONG) bila tak ada tombol; bx=1 bila AL bukan nol; bx=2 bila AL nol (kode pindai diperluas). Panjang 0/1/2 hanya dimiliki INKEY$",
                        "P":"berbagi tubuh alokasi+isi dengan CHR$; satu-satunya beda adalah konstanta panjang"}),
  13508:("SGNTEST_FAC",{"F":"membaca [0xB4] = FAC+2 (FAC HOPPER di 0xB2, ditetapkan mandiri)",
                        "P":"jmp ke 13494, tubuh SGNTEST yang sama dengan varian [si+2] dan [si+6]"}),
  9338:("SUB!_FAC",   {"F":"si = 0xB2 = FAC; varian ini memasok FAC sebagai operan, bukan penunjuk dari pemanggil",
                        "P":"jmp ke 9349, jalur yang melewati xor al,0x80 di 9355 -- pembalik tanda milik SUB!"}),
  9359:("ADD!_FAC",   {"F":"si = 0xB2 = FAC",
                        "P":"jmp ke 9370, jalur ADD! yang MELEWATI xor al,0x80; kontras langsung dengan @9338"}),
  18311:("ARITH!_FAC",{"F":"si = 0xB2 = FAC",
                        "P":"jmp ke 18322, tubuh ARITH! yang sama"}),
  23272:("PRINT#",    {"S":"call 23301 yang memetakan nomor berkas ke blok kendali, uji cmp byte [si],1 (mode keluaran), simpan ke [0x648] sebagai sasaran; lalu set [0x7D6]=0 (0=PRINT, 1=WRITE) dan masuk tubuh PRINT bersama",
                        "A":"kedua situs panggilan didahului mov bx,1 -- nomor berkas"}),
  11523:("SOUND",      {"S":"port speaker 42h/43h/61h; cmp bx,0x25 menolak nilai <37",
                        "A":"bx = 300/400/600 di situs panggilan = frekuensi Hz; batas 37 = batas bawah SOUND GW-BASIC"}),
  22506:("DRAW",       {"A":"menerima variabel 0x972/0x97A yang ditugasi string makro DRAW",
                        "L":"isi variabel ditelusuri independen dari literal di segmen data"}),
  21497:("INT2SGL",    {"S":"mov ax,0x9000 = eksponen MBF untuk magnitudo 16-bit; neg bx bersyarat tanda; xor dx,dx",
                        "A":"24 situs, hasil selalu disimpan, argumen integer diwarisi di bx"}),
  11863:("CLS",        {"S":"pilih dl=39 atau 79 dari mode di [0x616], dh=24 -- sudut kanan-bawah layar",
                        "A":"7 situs, TANPA argumen register; CLS satu-satunya pernyataan BASIC berbatas layar penuh tanpa argumen"}),
 },
 "3DTTT.EXE": {
  45232:("RT_HEAPINIT", {"S":"membaca PSP:[2] -- kata batas memori yang diberikan DOS -- lalu memasang ds/es ke segmen DGROUP dan menghitung bp = puncak - 0x10; tak menyentuh satu pun variabel pengguna",
                       "P":"byte demi byte IDENTIK di ketiga biner, hanya konstanta segmennya berbeda (PAC-GAL 0x7a2, 3DTTT 0xb11, HOPPER 0x7c5)",
                       "A":"selalu panggilan PERTAMA kode pengguna, di situs 26, mendahului RT_STMTCTX dan TRAP_INIT"}),
  34878:("RT_STMTCTX",  {"S":"`mov al,5` ke satu byte konteks lalu mencatat sp ke kata titik-periksa pernyataan, kemudian memulihkan alamat kembali jauh -- pembukuan, tanpa keluaran",
                       "P":"bentuk yang sama persis di ketiga biner, hanya alamat datanya berbeda (PAC-GAL [0x20]/[0x1e], 3DTTT [0xba]/[0xb8], HOPPER [0xb8]/[0xb6])",
                       "A":"selalu panggilan KEDUA kode pengguna, di situs 38"}),
  31393:("END_STMT",    {"S":"jalur `clc / pushf / <rantai pembersih> / popf / jmp` -- kembar dari entry luar @31384 yang menguji bendera lebih dulu dan mengambil jalur `stc`; carry itulah yang membedakan dua ragam terminasi",
                       "A":"entry DALAM dipanggil dari TENGAH program (pernyataan END eksplisit), entry LUAR tepat satu kali di situs panggilan TERAKHIR kode pengguna -- terminator implisit di ujung program",
                       "P":"pasangan yang sama ada di ketiga biner: PAC-GAL 14238/14247, 3DTTT 31384/31393, HOPPER 15089/15098"}),
  # --- I/O berkas: simpan dan muat permainan ---
  34244:("OPEN",      {"S":"dipanggil tepat sesudah OPEN_MODE$ dengan bx = nomor berkas, dx = nama berkas, cx = 0 -- tiga operan yang persis dibutuhkan OPEN mode,#n,nama",
                       "A":"blok yang diawalinya SELALU berlanjut ke PRINT# dengan nomor berkas yang sama, dan ditutup @34111"}),
  34111:("CLOSE",     {"S":"memanggil helper @34539 yang juga dipanggil jalur terminasi @31384 -- pembersih berkas",
                       "A":"kedua situsnya berada tepat sesudah rangkaian PRINT# terakhir dan sebelum blok berpindah"}),
  29771:("WIDTH",     {"S":"pembungkus satu panggilan yang meneruskan bx ke penyetel lebar layar",
                       "A":"bx = 0x50 = 80 di kedua situsnya, dan letaknya dalam urutan pembuka baku KEY OFF / SCREEN 0 / WIDTH 80 / CLEAR"}),
  30851:("DEF_SEG=",  {"S":"seluruh tubuhnya `mov word [0x9a], bx` lalu retf -- menyimpan satu word segmen",
                       "V":"[0x9A] adalah word yang dibaca instruksi `mov ds, [0x9a]` di kode pengguna sebelum PEEK/POKE, peran yang sama seperti [0x98] di HOPPER"}),
  31384:("END_STMT",  {"S":"`clc / pushf / call <pembersih> / call <helper CLOSE @34539> / popf / jmp` -- menutup berkas lalu mengakhiri program",
                       "P":"bentuk yang sama persis ada di HOPPER @15098 dan PAC-GAL @14238, masing-masing di ujung alur permainannya"}),
  # --- KOREKSI: @36119/@36318 sempat dinamai STKPUSH/STKREAD. Itu INPUT. ---
  36119:("INPUT_ITEM", {"S":"memanen alamat kembali jauh (pop di / pop es) lalu membaca DUA byte sebaris -- cacah dan kode tipe -- dan menyimpan penunjuk daftar item di [0x71E]/[0x720] beserta sp di [0x722]/[0x724]. Itu pengumpul daftar argumen, bukan tumpukan FOR/NEXT",
                        "P":"setiap situsnya diikuti @36318 dalam 25 byte, dan pasangan itu SELALU didahului panggilan INPUT yang membawa alamat literal prompt"}),
  36318:("INPUT_DONE", {"S":"membaca [0x722] lalu menelusuri daftar item MUNDUR sambil menguji cmp cl,3 -- memproses daftar yang sudah dikumpulkan @36119",
                        "V":"alamat yang dibawanya di situs 12581 adalah alamat yang persis di-LEN sembilan instruksi kemudian di 12590, jadi ia menulis variabel string TUJUAN; prompt di situs itu `Please enter your name? `"}),
  # --- KOREKSI: @33045 sempat dinamai ON_GOSUB. Ia ON ... GOTO. ---
  33045:("ON_GOTO",  {"S":"tubuhnya diawali `xor ah,ah`, dan di 33067 ada `or ah,ah` / `je` yang MELEWATI `push dx` (alamat kembali) sekaligus `inc [0x61a]` (pencacah kedalaman GOSUB). Tanpa keduanya, yang tersisa hanyalah lompatan lewat tabel",
                      "V":"entry TUMPANG-TINDIH di 33044 adalah `mov ax,0xE432` (b8 32 e4) yang memakai dua byte yang sama sebagai `xor ah,ah`; masuk lewat sana ah != 0 sehingga push dan pencacah DIJALANKAN -- itulah bentuk ON..GOSUB-nya. Seluruh situs 3DTTT menuju 33045"}),
  30869:("CLEAR",     {"S":"xor bx,bx; mov dx,bx menandai kedua argumen dihilangkan, lalu ukuran dibakukan ke 0x200 dan ditolak bila di bawah 0x180; batasnya dibulatkan ke alamat GENAP lewat inc bx; and bl,0xFE",
                        "V":"hasilnya disimpan ke [0x5F4] setelah diuji terhadap [0x5F2] -- [0x5F4] adalah penunjuk pemindai heap string 3DTTT yang ditetapkan di iterasi #9 saat membongkar alokatornya"}),
  26774:("SND_TIMER_OFF",{"S":"in al,0x61 lalu and al,0xFC dan out 0x61,al membersihkan kedua bit penyala pengeras suara; sesudahnya, dari segmen 0, word di 0x3C0 dan 0x3C2 disalin ke slot vektor INT 8 di 0x20 dan 0x22 -- memulihkan penangan timer yang disimpan -- dan 0 ditulis dua kali ke port PIT 0x40",
                        "V":"rutin yang dipanggilnya di 0x9D90 adalah pelepas simpul dari rantai berkait: ia menyusuri rantai dari 0x602, melepas simpul yang ada di si, dan mendorongnya ke daftar bebas di 0x5FE. Region 40336-40376 dibongkar sendiri"}),
  35081:("TRAP_INIT", {"S":"menolkan tepat 0x69 = 105 byte mulai 0x679, lalu membersihkan byte tepat sebelumnya di 0x678",
                        "V":"0x679 adalah basis tabel jebakan peristiwa: pembantu di 0x8A57 pada biner yang sama menghitung alamat rekaman sebagai 0x679 + n*5, dan 105 = 21 x 5 rekaman"}),
  # --- tombol fungsi lunak (iterasi lanjutan, dipandu jejak eksekusi) ---
  28326:("KEY_DISPLAY",{"S":"memetakan argumen ke tiga keadaan {0,1,2}, membandingkan dengan byte status [0x11], menuliskannya balik, dan memanggil penerap HANYA bila berubah",
                        "P":"entry tetangga @28353 menyusuri tabel sepuluh tombol lunak di 0x16 dan mencetak F<n> beserta isinya, jadi [0x11] memang mengatur tampilan tombol lunak dan ketiga keadaannya adalah ON, OFF, dan LIST"}),
  28353:("KEY_LIST",  {"S":"mov bx,0x16 lalu mov cx,0xA -- SEPULUH entri; tiap putaran memancarkan 0x46 huruf F, nomornya, spasi 0x20, lalu isi string yang dibaca lewat panjang di [bx] dan penunjuk di [bx+2]",
                        "T":"langkah antar-entri 4 byte dengan word panjang diikuti word penunjuk -- tata letak deskriptor string BASIC"}),
  # --- jebakan peristiwa (iterasi #20) ---
  35565:("ON_KEY_GOSUB",{"S":"menguji argumen terhadap batas kelas 0x0E pada indeks dasar 3, menghitung alamat rekaman sebagai 0x679 + n*5 lewat 0x8A57, lalu MENYIMPAN alamat penangan jauh ke [bx+1] dan [bx+3] rekaman 5-byte itu",
                        "V":"tabel di 0x679 adalah tabel jebakan peristiwa: penangan INT 9 di 35425 membaca port 0x60, mengurangi 0x3B (kode pindai F1) dan membatasi 10 tombol fungsi; rutin di @35081 menolkan tepat 0x69 = 105 = 21x5 byte di sana. Kedua region dibongkar sendiri"}),
  35625:("KEY_ONOFF", {"S":"menguji bx dalam 1..14 (or bx,bx; je; dec bx; cmp bx,0xE; jae) lalu di 35703 bercabang atas dl bernilai 0, 1, atau 2 ke tiga jalur berbeda -- tiga keadaan KEY(n) ON, OFF, dan STOP",
                        "P":"memakai indeks dasar kelas cl=3 dan pembantu alamat rekaman 0x8A57 yang SAMA dengan ON_KEY_GOSUB @35565"}),
  34170:("OPEN_MODE$",{"S":"menolak string kosong, mengambil karakter PERTAMA dari data deskriptor, membesarkannya dengan and bl,0xDF, lalu mengirim ke empat cabang yang masing-masing menghasilkan nilai berbeda",
                        "L":"keempat literal yang dibandingkan adalah 0x49 I, 0x4F O, 0x52 R, dan 0x41 A -- persis keempat huruf mode OPEN di BASIC, dan hasilnya 1, 2, 4, 8"}),
  32206:("VAL",       {"S":"mov si,[bx+2] mengambil penunjuk data deskriptor string, memindainya, lalu jmp 0x939E -- pelepas string SEMENTARA yang sudah dibuktikan di sec. 16, jadi string itu memang dikonsumsi dan dilepas",
                        "D":"menulis 8 ke [0x8B6], byte tipe yang SAMA dipakai keluarga READ, dan 8 adalah kode tipe presisi ganda"}),
  28693:("SCREEN_STMT",{"S":"dua argumen masing-masing diuji cmp dh,8 dan cmp dl,8 -- batas nomor HALAMAN tampilan -- lalu berakhir di BIOS int 10h ah=0x05, pilih halaman aktif; byte mode [0x5E4] ikut dibaca",
                        "A":"6 situs lewat akumulator argumen dengan pemeriksaan arity cmp ah,3"}),
  # --- pasangan kursor (iterasi #15); dipisahkan lewat pemetaan register BIOS ---
  28912:("CSRLIN",    {"S":"xor bh,bh; mov bl,[0x53] mengembalikan slot itu apa adanya sebagai bilangan, tanpa penyesuaian",
                        "V":"penyetel kursor di 26955 memuat word di [0x53] ke dx, lalu xchg dl,dh menaruh BYTE [0x53] di DH, dan 26961 memanggil BIOS ah=2 yang membaca DH sebagai BARIS. Region 26933-26963 dibongkar sendiri"}),
  29775:("POS",       {"S":"memanggil 26921 yang membaca [0x54] dan menguranginya satu, lalu menaikkannya kembali kecuali byte tipe [0xBA] bernilai 4 -- hasil akhirnya kolom 1-berbasis seperti yang dikembalikan POS",
                        "V":"pada penyetel kursor yang sama, xchg dl,dh menaruh BYTE [0x54] di DL, dan BIOS ah=2 membaca DL sebagai KOLOM"}),
  # --- trio substring (iterasi #14); pengekstrak bersama 0x8450 membuktikan peran cx dan dx ---
  33685:("LEFT$",     {"S":"xor cx,cx menyetel offset AWAL ke nol lalu masuk tubuh bersama; pengekstrak di 33872 memakai cx sebagai awal dan dx sebagai cacah, dan mengapit dx terhadap panjang di [bx]",
                        "P":"berbagi tubuh 33703 dan pengekstrak 33872 dengan @33694 dan @33708; ketiganya hanya berbeda pada cara offset awal dihitung"}),
  33694:("RIGHT$",    {"S":"mov cx,[bx]; sub cx,dx menyetel offset awal ke PANJANG dikurangi cacah -- persis titik mula RIGHT$",
                        "P":"berbagi pengekstrak 33872 dengan LEFT$ dan MID$"}),
  33708:("MID$",      {"S":"dec dx mengubah posisi awal BASIC yang 1-berbasis menjadi 0-berbasis, lalu mengapit AWAL maupun CACAH terhadap panjang -- dua argumen, tak seperti LEFT$ dan RIGHT$ yang satu",
                        "P":"berbagi pengekstrak 33872 dengan LEFT$ dan RIGHT$"}),
  # --- ABS, uji-nol FAC, dan rutin berargumen SEBARIS (iterasi #12) ---
  29906:("ABS",        {"S":"and byte ptr [0xB6], 0x7F membersihkan bit tanda MBF dan tidak menyentuh apa pun lagi",
                        "F":"0xB6 = 0xB4+2, byte yang memuat bit tanda pada FAC tunggal 3DTTT"}),
  29915:("ABS",        {"S":"badan sama dengan @29906, hanya prolog operannya berbeda (0x75ED, bukan 0x75E2)",
                        "P":"berbagi instruksi pembersih tanda yang sama persis"}),
  29895:("NONZERO!_FAC",{"S":"xor bx,bx lalu dec bx menghasilkan 0 atau -1, FALSE/TRUE milik BASIC",
                        "F":"menguji [0xB7] = 0xB4+3, byte eksponen FAC tunggal, yang nol tepat ketika bilangannya nol"}),
  29924:("SCALE2!",    {"S":"pop si; pop ds mengambil ALAMAT KEMBALI ke ds:si, lodsb membaca satu byte dari aliran instruksi pemanggil, lalu push ds; push si mengembalikan alamat yang sudah maju satu byte -- argumen SEBARIS. Byte itu ditambahkan ke [0xB7], byte eksponen FAC, dijaga cmp ...,0 agar nol tetap nol; menambah N ke eksponen MBF berarti mengali dengan 2^N",
                        "A":"pada keempat belas situs, byte sesudah lcall 5-byte selalu konstanta kecil (0x01 atau 0x04) dan instruksi sah berikutnya mulai 6 byte sesudah situs -- satu byte data memang dilewati"}),
  # --- keluarga string dan READ (iterasi #10); KOREKSI STROUT -> LEN ---
  33452:("LEN",        {"S":"push word ptr [bx] mendorong word PANJANG dari deskriptor, memanggil pelepas string sementara, lalu pop bx mengembalikan word yang sama sebagai hasil -- yang keluar adalah panjangnya, bukan isinya",
                        "A":"15 situs memakai hasilnya sebagai BILANGAN: `sub bx,0x1C; neg bx` untuk memusatkan teks di 4894 dan 5092, dan `or bx,bx; jne` untuk menguji string kosong di 12595"}),
  33459:("ASC",        {"S":"cmp word ptr [bx],0 menolak string kosong; mov si,[bx+2] lalu mov si,[si] mengambil word PERTAMA dari datanya; mov bh,0 membuang byte kedua sehingga hanya karakter pertama tersisa",
                        "P":"entry tetangga LEN @33452, berbagi pemanggilan pelepas string sementara; bedanya hanya apa yang dikembalikan"}),
  34963:("READ!",      {"S":"menyetel byte tipe [0x8B6] lalu masuk tubuh bersama yang memindai teks dari penunjuk di [0x676], memeriksa pemisah koma 0x2C, dan MENYIMPAN KEMBALI penunjuk yang sudah maju ke [0x676] -- penunjuk yang bertahan antar panggilan, ciri daftar DATA; tidak ada satu pun panggilan perangkat",
                        "D":"nilai yang ditulis ke [0x8B6] adalah {2,3,4,8}, persis kode tipe deskriptor stub operan (2=%, 3=$, 4=!, 8=#)"}),
  34970:("READ#",      {"S":"entry sama menyetel [0x8B6]=8","D":"8 = kode tipe presisi ganda"}),
  34977:("READ%",      {"S":"entry sama menyetel [0x8B6]=2","D":"2 = kode tipe bilangan bulat"}),
  34984:("READ$",      {"S":"entry sama menyetel [0x8B6]=3 lalu bercabang di 35041 (cmp al,3) ke jalur string, bukan ke FAC 0xB4","D":"3 = kode tipe string"}),
  35922:("INPUT#_BEGIN",{"S":"memvalidasi deskriptor berkas lalu cmp byte ptr [si],2 MENOLAK mode 2; menyimpan si ke [0x616] dan memasang vektor pengambil karakter di [0x71C]; pemindainya menangani kutip 0x22, koma 0x2C, dan akhir baris 0x0D/0x0A",
                        "P":"menulis slot perangkat [0x616] yang sama yang dinolkan PRINT_BEGIN dan diisi PRINT#, tetapi menerima mode yang berlawanan"}),
  29118:("CONCAT$",    {"S":"mov bx,[si] lalu add bx,[di] MENJUMLAHKAN kedua panjang deskriptor, jo memeriksa limpahan, alokasi sepanjang jumlah itu, lalu dua kali pemanggilan penyalin 0x71E4 -- sekali per sumber",
                        "A":"14 situs, dua argumen register (ax dan bx) yang keduanya deskriptor string"}),
  # --- salin-FAC (iterasi #8) ---
  29431:("FACSTORE!",  {"S":"simpan si,di ke [0x5E6]/[0x5E8]; si:=0xB4 lalu DUA movsw dari FAC ke memori pemanggil; pulihkan",
                        "T":"dua movsw = 4 byte tunggal; entry kembar di 29456 memakai si:=0xB0 dengan EMPAT movsw"}),
  # --- keluarga kali (iterasi #7); diturunkan MANDIRI per biner, bukan cocok-tanda-tangan (sec.9) ---
  31950:("MUL!",      {"S":"sub ah,0x81 / sub ch,0x80 / add ah,ch di 31974-31980 = eksponen dijumlahkan; xor al,cl gabung tanda",
                        "A":"prolog call 0x732b + mov di,0xB4 di 31944-31947 dilewati, jadi di dipasok pemanggil"}),
  31939:("MUL!_FAC",  {"F":"si = 0xB4 = FAC tunggal 3DTTT",
                        "P":"jmp ke 31950, tubuh MUL! yang sama"}),
  # --- varian entry (teknik g); tiap biner diturunkan MANDIRI, bukan cocok-tanda-tangan (sec.9) ---
  33479:("INKEY$",    {"S":"jalur je -> bx=0x124 string kosong; jalur jne -> panjang 1; jatuh -> panjang 2 untuk kode pindai diperluas",
                        "A":"10 situs; hasil selalu langsung ditugaskan ke variabel string lewat LET$ di dalam gelung jajak"}),
  29869:("SGNTEST_FAC",{"F":"membaca [0xB6] = FAC+2 (FAC 3DTTT di 0xB4, ditetapkan mandiri)",
                        "P":"jmp ke 29855, tubuh SGNTEST"}),
  32897:("ARITH!_FAC",{"F":"si = 0xB4 = FAC",
                        "P":"jmp ke 32908, tubuh ARITH!"}),
  36733:("PRINT#",    {"S":"call 36762 pemeta nomor-berkas lalu [0x82C]=0; keluarga lengkap lima bentuk terbaca di 36709-36760: PRINT, WRITE ([0x82C]=1), PRINT#, LPRINT ([0x616]=0xF2), WRITE#",
                        "A":"ketujuh situs panggilan didahului mov bx,1 -- nomor berkas"}),
  33117:("INT2SGL",    {"S":"mov ax,0x9000 = eksponen MBF untuk magnitudo 16-bit; neg bx bersyarat tanda; xor dx,dx",
                        "A":"11 situs, argumen integer di bx, hasil diteruskan"}),
  29388:("LET!",       {"S":"movsw x2; sub di,4; sub si,4 -- salin single 4 byte",
                        "T":"salin tepat 4 byte; tabel stub menetapkan AL=4 => SINGLE"}),
  29385:("FACSTORE!",  {"S":"mov si,0xB4 (FAC) lalu movsw x2",
                        "F":"0xB4 dirujuk 49 kali oleh 29 gugus rutin runtime berbeda = akumulator bersama"}),
  29411:("FACLOAD!",   {"S":"mov di,0xB4 (FAC) <- movsw x2",
                        "F":"0xB4 = akumulator bersama (29 gugus rutin)"}),
  32908:("ARITH!",     {"S":"dua operan 4 byte, uji tanda, xor bl,al",
                        "T":"dua operan 4 byte; tabel stub: AL=4 => SINGLE"}),
  31638:("ADD!",       {"S":"bongkar dua operan MBF lalu cmp ch,ah -- MEMBANDINGKAN eksponen, langkah penyelarasan PENJUMLAHAN (perkalian MENJUMLAHKAN eksponen, tidak membandingkan)",
                        "P":"entry SUB! di 31617 membalik bit tanda lalu masuk tubuh yang SAMA; negasi-lalu-tambah = pengurangan"}),
  33189:("LOAD!",      {"S":"bingkai error [604], muat 4 byte dari [si]",
                        "T":"muat 4 byte; tabel stub: AL=4 => SINGLE"}),
  36709:("PRINT_BEGIN",{"S":"menolkan [82C],[616],[82D] lalu retf",
                        "V":"[0x616] terbukti pemilih perangkat keluaran oleh rutin LAIN (0x8641)",
                        }),
  36435:("PRINT $;",   {"D":"stub 03 01 = STRING + pemisah ;",
                        "L":"menerima 'HELP ', '!!!   DRAW   !!!'"}),
  36455:("PRINT $ nl", {"D":"stub 03 02 = STRING + ganti baris",
                        "L":"menerima 'Please make your move:'"}),
  35846:("INPUT",      {"L":"menerima 'Please enter your name? '",
                        "S":"pop si/pop ds/lodsb -- baca argumen inline"}),
  29064:("LET$",       {"L":"menerima 'COMPUTER'",
                        "S":"call 0x9350 alokasi lalu salin"}),
  32958:("GOSUB",      {"S":"uji batas stack cmp sp,[5f0] + word inline",
                        "P":"inc [0x61a], dipasangkan RETURN yang dec"}),
  32999:("RETURN",     {"S":"dec word [0x61a] + js (RETURN without GOSUB)",
                        "P":"pasangan inc milik GOSUB"}),
  28098:("COLOR",      {"A":"1-3 argumen (2 arg x52, 3 arg x3); batas buffer 3",
                        "S":"akumulator byte, helper 0x6E8B, sensitif mode video"}),
  28124:("COLOR",      {"A":"pasangan 28098","S":"jalur sama + bingkai error"}),
  29219:("LOCATE",     {"A":"SELALU tepat 2 argumen (x77)",
                        "S":"akumulator byte, nilai teramati LOCATE 22,2 / 22,5"}),
  29245:("LOCATE",     {"A":"pasangan 29219","S":"jalur sama + bingkai error"}),
  33508:("CHR$",       {"S":"mov bx,1; call 0x931E -- alokasi string 1 byte",
                        "A":"nilai 24,25,27,26 = panah CP437, cocok label UP/DOWN/LEFT/RIGHT"}),
  29176:("STRCMP",     {"S":"repe cmpsb sesudah mengambil panjang minimum -- perbandingan byte-per-byte",
                        "A":"dua deskriptor string sebagai operan (bx dan ax)"}),
  # DIPULIHKAN: sempat diturunkan jadi STROP__maybe di iterasi #6 dengan alasan
  # "24/30 situs diikuti mov jadi hasilnya disimpan bukan dicabangkan". Penalaran
  # itu cacat -- perbandingan string memang mengembalikan nilai yang disimpan dulu.
  # Tubuhnya berakhir 'repe cmpsb' di ketiga biner. Lihat NEGATIVE-RESULTS sec. 11.
  27973:("CLS",        {"S":"pilih dl=39 atau 79 dari mode di [0x5E4], dh=24 -- sudut kanan-bawah layar",
                        "A":"11 situs, tanpa argumen register"}),
  33151:("FACNORM",    {"S":"baca [0xB0],[0xB2],[0xB3],[0xB5],[0xB6]; or bh,0x80 bit implisit; or dl,1 bendera pembulatan",
                        "F":"0xB0-0xB6 = region FAC (29 gugus rutin merujuknya)"}),
  28667:("ARG_C",      {"S":"mov cl,bl lalu jmp 0x6A6B -- bentuk akumulator argumen, helper 0x70DF",
                        "P":"berbagi jalur simpan 0x6A6B dengan akumulator COLOR dan LOCATE"}),
  33264:("CINT",       {"S":"sub ah,0x80 hilangkan bias eksponen MBF; mov cl,0x10/sub cl,ch = jumlah geseran; shr bx,cl selaraskan ke 16-bit; adc bx,0 = PEMBULATAN (membedakan CINT dari INT yang memotong); jo periksa limpahan",
                        "F":"membaca FAC [0xB4]/[0xB6] -- akumulator bersama 29 gugus rutin"}),
  # Bukti kedua akhirnya datang dari membaca tubuhnya SAMPAI HABIS (iterasi lanjutan),
  # bukan dari pola situs panggilan yang memang tidak membedakan.
  29851:("SGNTEST",    {"S":"uji eksponen or ah,ah, putar tanda ke carry",
                        "A":"16 dari 16 situs panggilan langsung diikuti lompatan bersyarat (jne x10, je x4, ja, jae)"}),
  31617:("SUB!",       {"S":"xor al,0x80 membalik tanda lalu jmp ke tubuh ADD! -- negasi lalu tambah",
                        "P":"berbagi tubuh dengan ADD! di 31638"}),
  33792:("STRING$",    {"S":"or bx,bx uji cacah; mov al,dl/mov ah,dl gandakan kode karakter ke kedua paruh AX; alokasi lalu isi cx/2 word",
                        "A":"bx = cacah 80/78/3, dx = 205/196 karakter garis CP437"}),
  33799:("STRING$",    {"S":"pungut karakter PERTAMA dari deskriptor string lalu jmp 33762 = tubuh pengisi STRING$",
                        "P":"berbagi tubuh pengisi dengan STRING$ di 33792"}),
 },
}

print("Audit disiplin dua-bukti\n" + "="*72)
rows=[]
for T,tbl in EV.items():
    print("\n== %s =="%T)
    ok=maybe=0
    for off,(name,ev) in sorted(tbl.items(), key=lambda kv: kv[1][0]):
        kinds={k[0] for k in ev}          # S2 dihitung sebagai S
        n=len(kinds)
        if n>=2:
            print("  %-14s @%-6d  %d jenis bukti (%s)  DITERIMA"%(name,off,n,",".join(sorted(kinds))))
            ok+=1; final=name
        else:
            print("  %-14s @%-6d  %d jenis bukti (%s)  -> %s__maybe"
                  %(name,off,n,",".join(sorted(kinds)),name))
            maybe+=1; final=name+"__maybe"
        rows.append(dict(binary=T,offset=off,name=final,kinds=sorted(kinds),evidence=ev))
    print("\n  %d diterima, %d turun ke __maybe"%(ok,maybe))
json.dump(rows,open(os.path.join(ROOT,"name-evidence.json"),"w"),indent=1,ensure_ascii=False)
print("\n-> decompile/name-evidence.json")
