/* Dihasilkan oleh tracer/alat/bikin-sumber.py - jangan disunting tangan.
   Sumber: run/MENU.BAS (41 baris) */
window.SUMBER = window.SUMBER || {};
window.SUMBER["MENU"] = [
  "10 CLEAR ,36000:KEY OFF:SCREEN 0,0,0:CLS:WIDTH 80:ON ERROR GOTO 520",
  "20 GOSUB 500",
  "70  CLS:DEF SEG:POKE 106,0",
  "80  COLOR 3,0:LOCATE ,,0",
  "140 LOCATE 2,18:PRINT\"Menu #1 - Programs Available On This Diskette\"",
  "150 LOCATE 4,5:COLOR 0,7:PRINT\" A \";:COLOR 3,0:PRINT\" Wildcatter\"TAB(31);:COLOR 0,7:PRINT\" H \";:COLOR 3,0:PRINT\" Dominoes   \"TAB(57);:COLOR 0,7:PRINT\" O \";:COLOR 3,0:PRINT\" You Draw It       \"",
  "160 LOCATE 7,5:COLOR 0,7:PRINT\" B \";:COLOR 3,0:PRINT\" Othello\"TAB(31);:COLOR 0,7:PRINT\" I \";:COLOR 3,0:PRINT\" PC Golf  \"TAB(57);:COLOR 0,7:PRINT\" P \";:COLOR 3,0:PRINT\" Towers Of Atlantis\"",
  "170 LOCATE 10,5:COLOR 0,7:PRINT\" C \";:COLOR 3,0:PRINT\" Peg Leap \"TAB(31);:COLOR 0,7:PRINT\" J \";:COLOR 3,0:PRINT\" Head Coach\"TAB(57);:COLOR 0,7:PRINT\" Q \";:COLOR 3,0:PRINT\" Personal Biorhythms\"",
  "180 LOCATE 13,5:COLOR 0,7:PRINT\" D \";:COLOR 3,0:PRINT\" Blackjack\"TAB(31);:COLOR 0,7:PRINT\" K \";:COLOR 3,0:PRINT\" Match        \"TAB(57);:COLOR 0,7:PRINT\" R \";:COLOR 3,0:PRINT\" Sports Predicting\"",
  "181 LOCATE 16,5:COLOR 0,7:PRINT\" E \";:COLOR 3,0:PRINT\" Mastermind\"TAB(31);:COLOR 0,7:PRINT\" L \";:COLOR 3,0:PRINT\" Nevada Dice  \"TAB(57);:COLOR 0,7:PRINT\" S \";:COLOR 3,0:PRINT\" Killer Maze\"",
  "182 LOCATE 19,5:COLOR 0,7:PRINT\" F \";:COLOR 3,0:PRINT\" Sea Battle\"TAB(31);:COLOR 0,7:PRINT\" M \";:COLOR 3,0:PRINT\" Eye & Hearing Test\"TAB(57);:COLOR 0,7:PRINT\" T \";:COLOR 3,0:PRINT\" Boggy Marsh\"",
  "183 LOCATE 22,5:COLOR 0,7:PRINT\" G \";:COLOR 3,0:PRINT\" Hangman\"TAB(31);:COLOR 0,7:PRINT\" N \";:COLOR 3,0:PRINT\" Tic Tac Toe \"TAB(57);:COLOR 0,7:PRINT \" U \";:COLOR 3,0:PRINT\" Menu #2\"",
  "190 LOCATE 24,14:COLOR 15,0:PRINT\"*****\";:COLOR 3,0:PRINT\" Strike Key Corresponding To Program Desired \";:COLOR 15,0:PRINT\"*****\":COLOR 3,0",
  "250 POKE 106,0",
  "260 R$=INKEY$:IF R$=\"\" THEN 260",
  "270 IF R$=\"A\" OR R$=\"a\" THEN RUN\"WILDCAT\"",
  "280 IF R$=\"B\" OR R$=\"b\" THEN RUN\"OTHELLO\"",
  "290 IF R$=\"C\" OR R$=\"c\" THEN RUN\"PEGLEAP\"",
  "300 IF R$=\"D\" OR R$=\"d\" THEN RUN\"21\"",
  "301 IF R$=\"E\" OR R$=\"e\" THEN RUN\"MASTER\"",
  "302 IF R$=\"F\" OR R$=\"f\" THEN RUN\"SUB\"",
  "303 IF R$=\"G\" OR R$=\"g\" THEN RUN\"HANGMAN\"",
  "310 IF R$=\"H\" OR R$=\"h\" THEN RUN\"DOMINOES\"",
  "320 IF R$=\"I\" OR R$=\"i\" THEN RUN\"GOLF\"",
  "330 IF R$=\"J\" OR R$=\"j\" THEN RUN\"FOOTBALL\"",
  "340 IF R$=\"K\" OR R$=\"k\" THEN RUN\"MATCH\"",
  "341 IF R$=\"L\" OR R$=\"l\" THEN RUN\"CRAPS\"",
  "342 IF R$=\"M\" OR R$=\"m\" THEN RUN\"HEAREYE\"",
  "343 IF R$=\"n\" OR R$=\"N\" THEN RUN\"tictac\"",
  "350 IF R$=\"O\" OR R$=\"o\" THEN RUN\"DRAW\"",
  "360 IF R$=\"P\" OR R$=\"p\" THEN RUN\"TOWERS\"",
  "370 IF R$=\"Q\" OR R$=\"q\" THEN RUN\"BIO\"",
  "380 IF R$=\"R\" OR R$=\"r\" THEN RUN\"STATS\"",
  "381 IF R$=\"S\" OR R$=\"s\" THEN RUN\"MAZE\"",
  "382 IF R$=\"T\" OR R$=\"t\" THEN RUN\"BOGGY\"",
  "383 IF R$=\"U\" OR R$=\"u\" THEN RUN\"MENU2\"",
  "390 GOTO 260",
  "500 FOR A=1 TO 10:ON KEY(A) GOSUB 510:KEY(A) ON:NEXT",
  "510 RETURN",
  "520 IF ERR=53 THEN RUN\"menu",
  "530 ON ERROR GOTO 0",
];
